from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from adapters.historical_run_backfill import HistoricalRunBackfillRecord


DEFAULT_OUTPUT = Path(r"D:\agent_test\outputs\offline_learning\historical_run_backfill_seed.jsonl")


def _seed_records() -> list[HistoricalRunBackfillRecord]:
    return [
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_fulltrain_20260418_155339",
            experiment_family="mcmc_fulltrain",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=1000000,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=26.1572,
            ssim=0.8826,
            lpips=0.19187,
            num_gs=1000000,
            unity_result="visual_fail",
            run_useful=True,
            role="benchmark",
            issue_type="framework",
            failure_reason="離線 LPIPS 最佳，但 Unity 白霧與 halo 明顯，僅能作為離線 benchmark。",
            next_recommendation="保留為 benchmark，不作 Unity deployment winner。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_fulltrain_20260419_143927",
            experiment_family="mcmc_capmax_fulltrain",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=26.0209,
            ssim=0.8803,
            lpips=0.19602,
            num_gs=750000,
            unity_result="candidate",
            run_useful=True,
            role="unity_candidate",
            issue_type="mixed",
            failure_reason="成本下降明顯且 Unity 觀感優於 1M，但畫質仍未通過可交付門檻。",
            next_recommendation="保留為成本折衷版，比較 antialiased 與 export-side probe。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_aa_fulltrain_20260420_032355",
            experiment_family="mcmc_capmax_aa_fulltrain",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=True,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=26.1582,
            ssim=0.8810,
            lpips=0.19529,
            num_gs=750000,
            unity_result="candidate",
            run_useful=True,
            role="unity_candidate",
            issue_type="unity_render",
            failure_reason="750k 路線中最佳 Unity 候選，但仍有白霧、halo、拖影，未達可交付品質。",
            next_recommendation="保留為當前 Unity 候選，改查 export-side 與新框架。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="export_probe_min_opacity_001_20260506",
            experiment_family="unity_export_probe",
            contract_stage="export_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=True,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            unity_result="visual_fail",
            run_useful=False,
            role="failed_probe",
            issue_type="export",
            failure_reason="大量刪除低透明 splat 只提升 FPS，白霧與破碎感仍在。",
            next_recommendation="停止延伸 export min_opacity 小矩陣。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="export_probe_percentile_995_20260506",
            experiment_family="unity_export_probe",
            contract_stage="export_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=True,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            unity_result="visual_fail",
            run_useful=False,
            role="failed_probe",
            issue_type="export",
            failure_reason="只砍最極端大 splat，對白霧、halo、拖影幾乎無效。",
            next_recommendation="停止延伸 percentile 小矩陣。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="glomap_mcmc_mid_probe_20260420_182258",
            experiment_family="mcmc_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=1000000,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=24.100,
            ssim=0.8554,
            lpips=0.2280,
            num_gs=1000000,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="未打贏 U_base + MCMC @ 7000，不具升 full train 價值。",
            next_recommendation="不升 full train，不再優先延伸上游交叉組合。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="aliked_lg_mcmc_mid_probe_20260420_184019",
            experiment_family="mcmc_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=1000000,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=22.689,
            ssim=0.8183,
            lpips=0.2740,
            num_gs=1000000,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="data",
            failure_reason="ALIKED + LightGlue 上游在 MCMC 下顯著差於 U_base + MCMC。",
            next_recommendation="不升 full train，不回頭作正式主線。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_aa_noiselr_mid_probe_20260420_230044",
            experiment_family="mcmc_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=True,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=100000.0,
            psnr=24.032,
            ssim=0.8541,
            lpips=0.2300,
            num_gs=750000,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="noise_lr=100000 未形成穩定改善，LPIPS 反而略差。",
            next_recommendation="不升 full train，不再優先測低 noise_lr。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_aa_minopa_mid_probe_20260420_224639",
            experiment_family="mcmc_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=True,
            random_bkgd=False,
            mcmc_min_opacity=0.01,
            mcmc_noise_lr=500000.0,
            psnr=24.134,
            ssim=0.8558,
            lpips=0.2278,
            num_gs=750000,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="min_opacity=0.01 僅有弱訊號，仍明顯落後 1M MCMC。",
            next_recommendation="不升 full train，不作主線預設。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_aa_randbkgd_mid_probe_20260420_231421",
            experiment_family="mcmc_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=True,
            random_bkgd=True,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=24.122,
            ssim=0.8562,
            lpips=0.2282,
            num_gs=750000,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="random_bkgd=True 只有輕微信號，不足以升 full train。",
            next_recommendation="不作正式預設，除非新資料再證明其穩定性。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_aa_randbkgd_minopa_mid_probe_20260505_232738",
            experiment_family="mcmc_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=True,
            random_bkgd=True,
            mcmc_min_opacity=0.01,
            mcmc_noise_lr=500000.0,
            psnr=24.3235,
            ssim=0.8573,
            lpips=0.22727,
            num_gs=750000,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="雙弱訊號組合略優於單變數 probe，但仍輸給 U_base + MCMC @ 7000。",
            next_recommendation="不升 full train，MCMC 小參數線到此收斂。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="app_opt_h_d0_fulltrain_20260418_124945",
            experiment_family="default_fulltrain",
            contract_stage="train_complete",
            train_mode="default",
            cap_max=None,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=None,
            mcmc_noise_lr=None,
            psnr=20.0509,
            ssim=0.7669,
            lpips=0.27352,
            num_gs=497527,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="app_opt full train 離線品質明顯劣化，證實早期短跑訊號不能代表長跑勝利。",
            next_recommendation="維持 app_opt 為歷史負向方向，不回到正式主線。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="sh1_h_d0_fulltrain_20260418_135309",
            experiment_family="default_fulltrain",
            contract_stage="train_complete",
            train_mode="default",
            cap_max=None,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=None,
            mcmc_noise_lr=None,
            psnr=21.8149,
            ssim=0.8017,
            lpips=0.25826,
            num_gs=495251,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="sh_degree=1 full train 最終仍輸給正式基準，屬於典型短跑假訊號。",
            next_recommendation="不再把 sh_degree=1 當正式優化方向。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_500k_mid_probe_20260419_092519",
            experiment_family="mcmc_capmax_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=500000,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=23.7694,
            ssim=0.8499,
            lpips=0.23658,
            num_gs=500000,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="500k cap_max probe 顯著落後 750k 與 1M，壓縮過頭。",
            next_recommendation="不延伸 500k 線，維持 750k 作成本折衷候選。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_mcmc_capmax_750k_mid_probe_20260419_092519",
            experiment_family="mcmc_capmax_probe",
            contract_stage="train_complete",
            train_mode="mcmc",
            cap_max=750000,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=0.005,
            mcmc_noise_lr=500000.0,
            psnr=24.0200,
            ssim=0.8545,
            lpips=0.22920,
            num_gs=750000,
            unity_result="not_tested",
            run_useful=True,
            role="unity_candidate",
            issue_type="parameter",
            failure_reason="7k probe 證實 750k 在成本折衷上可行，後續才有 full train 與 Unity 驗證價值。",
            next_recommendation="升 full train，作為 1M benchmark 的成本折衷候選。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_plain_mid_probe_20260418_142136",
            experiment_family="default_mid_probe",
            contract_stage="train_complete",
            train_mode="default",
            cap_max=None,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=None,
            mcmc_noise_lr=None,
            psnr=23.4453,
            ssim=0.8420,
            lpips=0.24958,
            num_gs=429942,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="default plain 7k probe 明顯弱於後續 MCMC 主線，沒有保留價值。",
            next_recommendation="保留為歷史對照，不回頭延伸 default plain。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_app_opt_mid_probe_20260418_142136",
            experiment_family="default_mid_probe",
            contract_stage="train_complete",
            train_mode="default",
            cap_max=None,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=None,
            mcmc_noise_lr=None,
            psnr=22.6513,
            ssim=0.8299,
            lpips=0.25920,
            num_gs=417085,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="app_opt 7k probe 已顯示弱勢，後續 full train 也證實失敗。",
            next_recommendation="將 app_opt 定位為歷史負向方向。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_sh1_mid_probe_20260418_142136",
            experiment_family="default_mid_probe",
            contract_stage="train_complete",
            train_mode="default",
            cap_max=None,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=None,
            mcmc_noise_lr=None,
            psnr=23.2087,
            ssim=0.8370,
            lpips=0.25582,
            num_gs=423690,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="sh_degree=1 7k probe 沒有建立長期優勢，後續 full train 亦證實失敗。",
            next_recommendation="不再把 sh_degree=1 當主線候選。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_opacity_reg_001_mid_probe_20260418_145232",
            experiment_family="default_mid_probe",
            contract_stage="train_complete",
            train_mode="default",
            cap_max=None,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=None,
            mcmc_noise_lr=None,
            psnr=23.0546,
            ssim=0.8336,
            lpips=0.26740,
            num_gs=316312,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="opacity_reg=0.01 在 default 7k probe 下表現更差，沒有形成可延伸優勢。",
            next_recommendation="不再將 opacity_reg 單獨視為 default 主線突破口。",
            label_source="history_backfill",
        ),
        HistoricalRunBackfillRecord(
            run_id="u_base_pose_opt_mid_probe_20260418_145232",
            experiment_family="default_mid_probe",
            contract_stage="train_complete",
            train_mode="default",
            cap_max=None,
            antialiased=False,
            random_bkgd=False,
            mcmc_min_opacity=None,
            mcmc_noise_lr=None,
            psnr=23.2966,
            ssim=0.8391,
            lpips=0.25096,
            num_gs=427813,
            unity_result="not_tested",
            run_useful=False,
            role="failed_probe",
            issue_type="parameter",
            failure_reason="pose_opt 7k probe 沒有打贏正式基準，屬於歷史負向支線。",
            next_recommendation="不再優先測 pose_opt。",
            label_source="history_backfill",
        ),
    ]


def build_seed_records() -> list[dict]:
    return [asdict(record) for record in _seed_records()]


def write_jsonl(records: Iterable[dict], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the historical run backfill seed dataset.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    records = build_seed_records()
    write_jsonl(records, args.output)
    print(f"[OK] wrote {len(records)} records -> {args.output}")


if __name__ == "__main__":
    main()
